"""empty message

Revision ID: 8c7ed9fee978
Revises: c929c827a017
Create Date: 2024-10-26 17:46:36.807617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7ed9fee978'
down_revision = 'c929c827a017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))  # Allow null temporarily

    # Optionally, you can add logic here to update existing rows with a default password if needed.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
